### ISSUE TITLE
Allow expected properties other than types

### ISSUE THREAD

**Issue by AlexKnauth** [stchang/macrotypes#1]
There should be a way of propagating expected properties other than types.

```racket
(define-typed-syntax needs-expected-foo
  [(needs-expected-foo e) ⇐ foo F-expected ≫
   [⊢ e ≫ e- ⇒ : τe]
   --------
   [⊢ (wrap-foo- e-) ⇒ : (→ F-expected τe)]])

(define-typed-syntax propagate-expected-foo
  [(propagate-expected-foo e F) ≫
   [⊢ e ≫ e- (⇐ foo F) (⇒ : τe)]
   --------
   [⊢ e- ⇒ : τe]])
```

From these I would want an expression like

```racket
(propagate-expected-foo (needs-expected-foo 5) String)
```

To typecheck as `(→ String Int)`.

**Comment by stchang** [comment]
Yes, I've wanted this, and @iitalics just brought it up as well.

Concretely, the change we need is that the left and right input/output arrows in a `define-typed-syntax` rule should not be treated specially, but rather be generalized (like in the premises). eg,
```
(define-typed-syntax thing
  [(thing e) (⇐ in-key1 key1-expected-val) (⇐ in-key2 key2-expected-val) ≫
 ....
 ---------
 [⊢ (thing- e-) (⇒ out-key1 out-val1) (⇒ out-key2 out-val2)]])
```

**Comment by stchang** [comment]
This is possible now. eg, see https://github.com/stchang/macrotypes/blob/master/turnstile-example/turnstile/examples/linear/lin2.rkt

added by https://github.com/stchang/macrotypes/commit/f457e2771a0c500a018aa518bba17310fcf6a6f3
