### ISSUE TITLE
The overridden #, prevents access to identifiers from the surrounding scope

### ISSUE THREAD

**Issue by SuzanneSoy** [stchang/macrotypes#22]
```racket
#lang turnstile/lang

(require (only-in racket/base [+ plus]))

(define-syntax (foo stx)
  #`#,(plus 1 2))

=> plus: unbound identifier in module (in phase 1, transformer environment) in: plus
```

In the unquoted form, it's impossible to use the identifier `plus` available in the surrounding scope. It's still possible to use `+` and other "built-in" identifiers, though (those from `racket/base` or `turnstile/lang`, I'd guess).

**Comment by AlexKnauth** [comment]
Did you forget the `for-syntax`?

**Comment by SuzanneSoy** [comment]
Yup… I was sure I had seen this problem yesterday on a more complex example, where removing the #`#, made it work. It must have been some other issue. Sorry about the noise!
