### ISSUE TITLE
Should be able to use Type at runtime

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#26]
For Cur, we should be able to use Type at runtime. 

Test:
```
#lang racket/base
(require turnstile/examples/dep-ind)

(Type 0)
```
Expected: Produces a runtime representation of `(Type 0)`
Actual: Displays "; Type: Cannot use type at run time"

**Comment by stchang** [comment]
Ah oops yeah. I fixed some of the types but not others. I'll check all of them.

**Comment by stchang** [comment]
fixed in https://github.com/stchang/macrotypes/commit/a90dcb7279d3ed86b388d04ea2ef0cadd428a568
