### ISSUE TITLE
Can't define datatypes in dep-ind, or dep-ind fixed

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#33]
```racket
#lang racket/base

(require turnstile/examples/dep-ind)

(define-datatype Nat : (Type 0)
  [z : Nat]
  [s : (Π ([x : Nat]) Nat)])

; /tmp/meow.rkt:5.0: define-datatype: type mismatch: expected Type, given (Type 1)
;   expression: (Type 0)
;   at: (Type 0)
;   in: (define-datatype Nat : * (z : Nat) (s : (Π ((x : Nat)) Nat)))
```

```racket
#lang racket/base

(require turnstile/examples/dep-ind-fixed)

(define-datatype Nat : (Type 0)
  [z : Nat]
  [s : (Π ([x : Nat]) Nat)])

; /tmp/meow.rkt:5.0: define-datatype: expected the literal symbol `:'
;   at: 0
;   in: (define-datatype Nat : (Type 0) (z : Nat) (s : (Π ((x : Nat)) Nat)))
```

Problem persists if I use `(Type 0)`, `Type`, or `*`.

**Comment by stchang** [comment]
Yah, so all constructors must be a function right now. (And they must consume all params and indices).
 [Here's the Nat example][1].

Should I fix it to be closer to cur's behavior?

[1]: https://github.com/stchang/macrotypes/blob/peano/turnstile/examples/tests/dep-ind-tests.rkt#L34-L36

**Comment by wilbowma** [comment]
Oh I somehow missed that. Okay, that makes sense.

No, we can fix that up in `cur-to-turnstile.rkt`.

**Comment by wilbowma** [comment]
But I would still call this a bug in the error message: why is it blaming `(Type 0)` or complaining about missing `:`?

**Comment by stchang** [comment]
should be fixed in https://github.com/stchang/cur (`turnstile-core` branch)
