### ISSUE TITLE
Can't use \Pi at run-time

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#34]
In Cur's current semantics, we need to be able to refer to \Pi types at run-time.

Test:
```racket
#lang racket/base

(require turnstile/examples/dep-ind)

(Π ([A : *]) A)
```

Expected: The run-time representation of `(Π ([A : *]) A)`

Actual: The following error message
```racket
; ∀: Cannot use type at run time
```

**Comment by stchang** [comment]
Does it matter what the runtime representation is? Right now it will be a quoted version of the syntax.

**Comment by wilbowma** [comment]
Not particularly, as long as it's not completely opaque. Quoted syntax is problem fine... although I'd be concerned about references to identifiers getting lost.

**Comment by stchang** [comment]
So will the runtime representation ever need to be reflected back to syntax?

**Comment by stchang** [comment]
Addressed in https://github.com/stchang/macrotypes/commit/8f6c2c1411506724c00f214e3491e0a90f4e721a

**Comment by wilbowma** [comment]
Hm. In order to support separate compilation, we'll probably need to reflect the runtime representation into a type. I haven't started addressing separation compilation though.

**Comment by stchang** [comment]
Ok I'll leave this open for now then.

**Comment by stchang** [comment]
moved to https://github.com/stchang/cur/issues/4
