### ISSUE TITLE
[mlish] typechecking does not terminate on recursive type

### ISSUE THREAD

**Issue by SuzanneSoy** [stchang/macrotypes#35]
```
#lang s-exp turnstile/examples/mlish
(define-type-alias (LL T) (→ (× T (LL T))))
(define (f -> (× Int (LL Int)))
  (tup 1 (ann f : (LL Int))))
```

The program above defines a lazy list of ones. Typechecking does not terminate, most likely because mlish tries to unify `(LL Int)` and `(→ (× Int (LL Int)))`, or something similar, and there is no guard detecting that (there's `occurs-check` in `type-constraints.rkt`, but it probably isn't called in this particular case).

**Comment by AlexKnauth** [comment]
Even
```racket
#lang s-exp turnstile/examples/mlish
(define-type-alias (LL T) (→ (× T (LL T))))
(define-type-alias LLInt (LL Int))
```
Causes this problem. We shouldn't allow recursive references in type alias at all. For normal type alias (not type constructor aliases), this throws an error, we need to find a way to do the same for type constructor aliases.

**Comment by stchang** [comment]
Right, `define-type-alias` is itself just an alias for a macro definition so it's infinitely expanding here.

A self-reference check would probably be the right thing to add as a first step.
