### ISSUE TITLE
Issues with inductive types with indices

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#36]
Inductive types have a subtle issue with how indices are handled in constructors. Let's consider the definition of Vector:
```racket
(define-datatype Vect [A : (Type 0)] : [i : Nat] -> (Type 0)
  [nil : (Π ([A : *]) (Π ([k : Nat]) (→ (Vect A (Z)))))]
  [cns : (Π ([A : *]) (Π ([k : Nat]) (→ A (Vect A k) (Vect A (S k)))))])
```

The problem is with the `nil` constructor. `nil` should take 1 argument as its index is a constant. But because `dep-ind-fixed` requires that all constructors take 3 telescopes (parameters, indices, and "other"), it takes 2.

In this presentation, the index argument in `nil` is a constant, so the argument `k : Nat` is spurious. The type of `(nil Nat (S (Z)))` is still `Vect Nat  (Z)`.

In general, the index arguments in the constructor are inseparable from the "rest" of the arguments; the indices and rest may be interdependent or nonexistent, so we cannot count on the pattern `(Pi ([A : TA] ...) (Pi ([I : TI] ...) (Pi ([r : Tr] ...) result)))`. We only know that every constructor takes all of the parameters, and that they come first.

**Comment by stchang** [comment]
Yes, I was going for a "simpler" pattern-based definition of `define-datatype`, which requires every constructor type to satisfy the same pattern.

This does lead to unused arguments, and more verbose elimination terms, but I was hoping it wouldn't matter.

But if this unworkable with cur, then I'll fix it to assume only parameters in the constructor types.

**Comment by wilbowma** [comment]
Well it's not unworkable yet, but I am concerned that there exist inductive types that don't fit this pattern, e.g., if an index can dependent on a recursive non-index argument. I admit I don't have any such construction of the top of my head, so maybe they're sufficiently abstruse as to not matter.

**Comment by stchang** [comment]
Ok I'll see what I can do.

I planned to experiment with syntax classes to replace the explicit patterns anyways ([something like what @iitalics did here][2]), so maybe the code to parse the constructor types can go in there.

[2]: https://groups.google.com/forum/#!topic/racket-users/y3jXpT_iIMo

**Comment by wilbowma** [comment]
Yeah, Cur uses syntax classes to handle all this, because it's just too complex to do otherwise. Cur also requires single-arity functions, to simplify computing parameters vs indices vs others. 

If you want primitive multi-arity functions, or pure pattern based definition... this may be a good enough definition for now.

**Comment by wilbowma** [comment]
I'm no longer confident I understand how inductives in turnstile work. They seem to be somewhat inconsistent. For example, the above vector type has 3 clear set of arguments: parameters, indices, and other. This is fine. However, the definition of List below, from the test suite, seems to only have 2: parameters, and others.

```racket
(define-datatype Vect [A : (Type 0)] : [i : Nat] -> (Type 0)
  [nil : (Π ([A : *])        (Π ([k : Nat]) (→ (Vect A (Z)))))] 
 ;          ^ parameters          ^          ^
 ;                                | indices  |
 ;                                           | other
  [cns : (Π ([A : *]) (Π ([k : Nat]) (→ A (Vect A k) (Vect A (S k)))))])

(define-datatype List [A : (Type 0)] : -> (Type 0)
  [null : (∀ (A)             (→ (List A)))]
 ;           ^ parameters     ^
 ;                            | indices and others
  [cons : (∀ (A) (→ A (List A) (List A)))])
```
As we can see, there's inconsistency in what different inductive types expect for the shape of their declarations.

Stranger, despite the declarations for List, the method for List still seems to think there is a distinction between indices and other:
```racket
 (elim-List ((null Nat))
            (λ () (λ ([l : (List Nat)]) Nat))
            (λ ()           (λ ()          (λ () (z))))
                ;^ indices     ^              ^
                ;              | "other"      |
                ;                             | inductive hypotheses
            (λ ()
              (λ ([x : Nat][xs : (List Nat)])
                (λ ([IH : Nat])
                  (s IH)))))
```

**Comment by stchang** [comment]
Yes, sorry, `dep-ind-fixed.rkt` no longer relies on separate groupings for parameters and indices.
 The groupings didnt make sense, eg, since some params could depend on previous ones, and thus werent sufficient to handle all our equality examples.

Instead, it now just checks whether each constructor's declared type has enough arguments to handle the `A`s and `i`s (I think like Cur does?), eg: https://github.com/stchang/macrotypes/blob/peano/turnstile/examples/dep-ind-fixed.rkt#L606-L610

But the elim clauses still work like before. Do I need to change them?

**Comment by wilbowma** [comment]
I see. It seems to expect either they be completely curried, or separated by parameters and indies then other. E.g., the following doesn't seem to type check, although if it were complete agnostic to grouping it should be an equivalent definition.

```racket
(define-datatype List [A : (Type 0)] : -> (Type 0)
  [null : (Π ((A : (Type 0))) (List A))]
  [cons : (Π ((A : (Type 0)) (a : A) (l : (List A))) (List A))])
```

I think the prune function could be adapted to handle this, but as Cur expected fully curried arguments, it doesn't really matter; I'm just trying to understand turnstile's behavior so I can target it properly.

Whatever the case, the methods and constructors should have similar behavior, since the type of a method is derived from the type of its constructor.

**Comment by stchang** [comment]
Oh oops, `prune` should call `uncur`. Basically, the plan is to make it like cur, with everything implicitly curried, even the methods, but at this point it's just a technicality, so I havent gotten to it yet.

**Comment by wilbowma** [comment]
Ah. Okay. So @mpoffald and I were going to add wrapper macros in the cur-to-turnstile, but maybe we should just modify turnstile directly.

**Comment by stchang** [comment]
That would be fine. But it might be annoying to change all the examples so you can leave it for me as well.

**Comment by stchang** [comment]
fixed in https://github.com/stchang/cur (which follows `cur` syntax)
