### ISSUE TITLE
"bad syntax" in inductive with no parameters/indices

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#37]
The following should be equivalence, I think, but the first definition causes "bad syntax" error. 

I suspect the problem is in https://github.com/stchang/macrotypes/blob/peano/turnstile/examples/dep-ind-fixed.rkt#L479, where the pattern requires the type of the inductive matches an identifier, i.e., `TY:id`. I suspect that this was introduce when the infinite hierarchy was added, and the syntax for `Type` was changed to `(Type i:nat)`

```racket
#lang racket/base
(require turnstile/examples/dep-ind-fixed)

(define-datatype Nat : -> (Type 0)
  (z : (Π () (Π () (Π () Nat))))
  (s : (Π () (Π () (Π ((n : Nat)) Nat)))))

(define-datatype Nat2 : *
  (z2 : (Π () (Π () (Π () Nat2))))
  (s2 : (Π () (Π () (Π ((n : Nat2)) Nat2)))))
```

**Comment by stchang** [comment]
Yes, you are right, there does seem to be some ambiguity in the match patterns now. I should just fix it so one dispatches to the other, like with your example.

**Comment by wilbowma** [comment]
Looks like this is still a problem in the dep branch, in `dep-ind-cur`

**Comment by stchang** [comment]
should be fixed in https://github.com/stchang/cur (`turnstile-core` branch)
