### ISSUE TITLE
change `#lang turnstile/lang` to `#lang turnstile/quick`

### ISSUE THREAD

**Issue by stchang** [stchang/macrotypes#38]
@AlexKnauth @iitalics 

I dont like the name `#lang turnstile/lang` because it's unintuitive and I always forget which is which.

I'm going to change it to `#lang turnstile/quick` or `#lang turnstile/quicklang` (drawing inspiration from `#lang web-server/insta`) unless you guys can come up with something better :)

**Comment by iitalics** [comment]
I'm all for changing it, and can't really think of a better name.

**Comment by iitalics** [comment]
I think I prefer `turnstile/quicklang` FWIW
