### ISSUE TITLE
Abstract over typed wrappers for defined variables

### ISSUE THREAD

**Issue by michaelballantyne** [stchang/macrotypes#44]
Implementations of typed definition forms often expand to a pattern like this:

```
(begin-
       (define-syntax x (make-rename-transformer (⊢ x- : τ)))
       (define- x- e-))
```

I'm working on a change to have `⊢` wrap the erased term in additional syntax to prevent its expansion during typechecking. In the case of variable definitions like this, however, I need to skip that extra wrapper so that `set!` works properly. So I'd end up changing all instances of this pattern to look like:

```
(begin-
       (define-syntax x (make-rename-transformer (⊢ x- : τ #:no-wrap)))
       (define- x- e-))
```

It seems like it would be better to abstract over the pattern. I propose adding a `define-typed-variable-rename` form to `typecheck.rkt`, such that we would write (in both macrotypes and turnstile examples):

```
(begin-
       (define-typed-variable-rename x ≫ x- : τ)
       (define- x- e-))
```

I don't think we should try to include the `define-` in the abstraction, because it could vary with the language being implemented.

Any thoughts on this API or it's name?

**Comment by stchang** [comment]
added in https://github.com/stchang/macrotypes/commit/82fa0a1a8dfe389d121aa17298ebc14fd83947bd
