### ISSUE TITLE
prune+sort gets rid of super type sometimes

### ISSUE THREAD

**Issue by AlexKnauth** [stchang/macrotypes#5]
In something like `(U Nat Int)`, I expect it to prune away `Nat` and keep `Int`, but that isn't always what happens. Sometimes it keeps both, and sometimes it keeps the `Nat` but drops the `Int`.

With the actual `Nat` and `Int` it's fine (since the sub-parts `Zero`, `PosInt`, and `NegInt` don't overlap with each other), but with more complicated subtyping relationships like `Term`s in Typed Rosette it's causing problems.

**Comment by AlexKnauth** [comment]
Relying on `remove-duplicates` probably isn't going to be the right thing for us. This simplified example fails on every case of pruning combining `A`s and `B`s:
```racket
#lang racket
(define (typecheck? x y)
  (match* {x y}
    [{'A 'A} #true]
    [{'A 'B} #true]
    [{'B 'A} #false]
    [{'B 'B} #true]))

(define (prune tys)
  (remove-duplicates tys (lambda (x y) (typecheck? y x))))
```
This never gives the right answer. It should be `'(B)` whenever both `A`s and `B`s are there, but it's always either `'(A)` (unsound!) or `'(B A)` (sound but not pruning) depending on whether `A` or `B` appears first in the list.

**Comment by AlexKnauth** [comment]
We'll need to go through all n choose 2 combinations ourselves, I think.

**Comment by stchang** [comment]
Do you have a concrete failing example? The problem is when the types overlap? What are `A` and `B` above?

**Comment by AlexKnauth** [comment]
Yeah these all give wrong answers
```racket
(prune (list 'A 'B))
(prune (list 'B 'A))
(prune (list 'A 'B 'B 'B))
(prune (list 'B 'A 'A 'A))
(prune (list 'A 'B 'B 'A))
(prune (list 'B 'A 'A 'B))
(prune (list 'A 'A 'B 'A 'A 'A 'B 'B))
```

**Comment by AlexKnauth** [comment]
Does this look reasonable?
```racket
;; filter-maximal : [Listof X] [X X -> Bool] -> [Listof X]
;; <? is a partial ordering predicate
(define (filter-maximal xs <?)
  (for/fold ([acc '()])
            ([x (in-list xs)])
    (merge-with x acc <?)))

;; merge-with : X [Listof X] [X X -> Bool] -> [Listof X]
;; <? is a partial ordering predicate
(define (merge-with x ys <?)
  (define (greater? y) (<? x y))
  (cond [(ormap greater? ys) ys]
        [else
         (define (lesser? y) (<? y x))
         (cons x (filter-not lesser? ys))]))
```

**Comment by stchang** [comment]
Is `A` a subtype of `B`? Is the problem that `remove-dups` expects a symmetric predicate?

**Comment by stchang** [comment]
> Does this look reasonable?

Seems ok. Still not sure why we need to go through all the combos.

Do you have a failing example with actual types?

**Comment by AlexKnauth** [comment]
Yes. It's with `(Term CNat)` and `(Term CInt)`.

**Comment by stchang** [comment]
I thought we were getting rid of Nat?

**Comment by AlexKnauth** [comment]
With the `Term` constructor we can leave it in. But even if we got rid of `Nat` there would be the same thing with `(Term CInt)` and `(Term CNum)`.

**Comment by stchang** [comment]
Ok, that's true.

**Comment by AlexKnauth** [comment]
Fixed by https://github.com/stchang/macrotypes/commit/f9199f6e3710018c2162f0453ae10ef164534063
