### ISSUE TITLE
Subtyping for Pi types is broken

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#64]
This should type check:
```
#lang cur/turnstile
((λ (f : (Π (x : (Type 0)) (Type 1))) f) (λ (x : (Type 0)) x))
```
(this runs in the `turnstile-scratch` branch of Cur)

The subtyping rule should be:
```
i < j
------------------------
Γ ⊢ (Type i) ≼ (Type j)

Γ ⊢ A ≡ A'
Γ, x : A ⊢ B ≼ B'
---------------------------------
Γ ⊢ Π (x : A). B ≼ Π (x : A'). B'
```

**Comment by stchang** [comment]
So it's not standard contravariance? `A` is equal to `A'`?

**Comment by wilbowma** [comment]
Yeah. IIRC, it can be contravariant but this is standard, due to nicer set theoretic semantics.

--

**Comment by stchang** [comment]
https://github.com/stchang/macrotypes/commit/ff7ee9f17005efc9028b47853285bf24a647a34b
