### ISSUE TITLE
Correct source locations

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#69]
I've been experimenting with the Cur-on-Turnstile Curnel, and getting bad source locations. Looking over the code, it looks like there are many places where `format-id` should pass in a `#:source`, and where `syntax` or `quasisyntax` should be replaced by `syntax/loc` and `quasisyntax/loc`.

If no objections, I'm going to start fixing these (probably by introducing some abstractions for automatically getting the right source location when possible).

**Comment by stchang** [comment]
yes please!

**Comment by stchang** [comment]
see #88

**Comment by stchang** [comment]
closing for now. open new ticket for additional problems.
