### ISSUE TITLE
#:error cannot reference attributes from right-hand side of infer arrow(?)

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#76]
I'm getting a strange error when I try to use attributes from the right hand-side of an infer arrow in a `#:error` message. Here is an example excerpt (full code in Cur).

```racket
(define-typed-syntax Π
  ; Predicative rule
  [(_ (x:id (~datum :) τₐ) τᵣ) ≫
   [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
   [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
   #:with k (max (syntax->datum #'i) (syntax->datum #'j))
   ------------------------------
   [⊢ (Π- τₐ- (λ (x-) τᵣ-)) ⇒ (Type k)]]

  ;; Error rules
  [(_ (x:id (~datum :) τₐ) τᵣ) ≫
   [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
   [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
   #:when (and (attribute i) (attribute j))
   -----------------
   [#:error (type-error #:src #'τₐ #:msg "Universe inconsistency: A function's argument and return types must exist in a consistent universe, but ~a lives in universe (Type ~a) while ~a lives in universe (Type ~a)."
                        #'τₐ
                        (attribute j)
                        #'τᵣ
                        #;(syntax-property #'τᵣ 'origin)
                        (attribute i))]])
```

I get an error that `(attribute j)` is unbound in the `type-error` call, despite `(attribute j)` definitely existing.

```
;... cur/cur-lib/cur/curnel/turnstile-impl/dep-ind-cur2.rkt:93:35: attribute: not bound as a pattern variable
;   at: j
;   in: (attribute j)
```

The blamed line is the second occurance of `(attribute j)`.

**Comment by wilbowma** [comment]
Might be more than just attributed from infer mode; this didn't work either:
```racket
  [(_ (x:id (~datum :) τₐ) τᵣ) ≫
   [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
   [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
   #:when (and (attribute i) (attribute j))
   #:with j^ (attribute j)
   -----------------
   [#:error (type-error #:src #'τₐ #:msg "Universe inconsistency: A function's argument and return types must exist in a consistent universe, but ~a lives in universe (Type ~a) while ~a lives in universe (Type ~a)."
                        #'τₐ
                        (attribute j^)
                        #'τᵣ
                        #;(syntax-property #'τᵣ 'origin)
                        (attribute i))]])
```

**Comment by stchang** [comment]
Turnstile conclusions are in an implicit (quasi) syntax template, so the two `(attribute j)` are not the same. You need to `syntax-unquote` if you want to use `attribute` in the conclusion.

**Comment by wilbowma** [comment]
That is very mysterious. Why do `#'\tau_a` and `#'\tau_r` get the right bindings, while `#'i` and `#'j` do no? (I changed them to explicit `attribute` calls when debugging)

**Comment by stchang** [comment]
Why is it mysterious? The second `(attribute j)` is essentially `#'(attribute j)` so if `j` is bound as an attribute for the first occurence, at phase 1, then it shouldnt be for the second occurrence, which is at phase 0.

**Comment by wilbowma** [comment]
It's mysterious because I would expect `(type-error ...)` to be executing in the same phase as any code in the premises, such as in the `#:when` clause, not automatically under a template. That is, I would expect `#:error` to behave similar to `syntax-parse`'s `#:fail`.

It also doesn't explain why only `i` and `j` are affected, while `\tau_a` and `\tau_r` get the right references. E.g., if I change the `attribute`'s back to `#'`, I get the error message:
`; TYPE-ERROR:.../InfList.rkt (9:36): Universe inconsistency: A function's argument and return types must exist in a consistent universe, but Inf lives in universe (Type j) while (Π/c A) lives in universe (Type i).`. Notice that `Inf` (the value of `#'\tau_a`) is replaced correctly, but `#'j` is just "j")

**Comment by stchang** [comment]
I'm not sure how the `attribute` macro works but probably `tau_a` and `tau_r` get to resolve as pattern variables while `attribute` does something else with its argument?

**Comment by wilbowma** [comment]
Yes, including some error checking to prevent an expected-pattern-variable from transforming into raw syntax. (which is why I changed it.) Consider the following code; why aren't `#'i` and `#'j` bound as pattern variables?

```racket
  [(_ (x:id (~datum :) τₐ) τᵣ) ≫
   [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
   [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
   -----------------
   [#:error (type-error #:src #'τₐ #:msg "Universe inconsistency: A function's argument and return types must exist in a consistent universe, but ~a lives in universe (Type ~a) while ~a lives in universe (Type ~a)."
                        #'τₐ
                        #'j
                        #'τᵣ
                        #'i)]]
```

**Comment by wilbowma** [comment]
(By the way, I tried `#,(attribute j^)` and got 
```racket
; .../cur/cur-lib/cur/curnel/turnstile-impl/dep-ind-cur2.rkt:92:24: unsyntax: illegal outside of quasisyntax
;   in: (unsyntax (attribute j^))
```
)

**Comment by wilbowma** [comment]
New theory: does the `#:error` conclusion result in all premises being ignored?

Inspecting turnstile seems to confirm this. The above rule gets transformed into essentially:
```racket
[(~and (_ (x:id (~datum :) τₐ) τᵣ)
       (~post (~fail (type-error #:src #'τₐ #:msg "Universe inconsistency: A function's argument and return types must exist in a consistent universe, but ~a lives in universe (Type ~a) while ~a lives in universe (Type ~a)"))
       [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
       [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
 #'(error (type-error #:src #'τₐ #:msg "Universe inconsistency: A function's argument and return types must exist in a consistent universe, but ~a lives in universe (Type ~a) while ~a lives in universe (Type ~a)"))]
```
So `#'i` and `#'j` are used before they are defined.

I expected it to be equivalent to:
```racket
[(~and (_ (x:id (~datum :) τₐ) τᵣ)
       [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
       [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
       (~post (~fail (type-error #:src #'τₐ #:msg "Universe inconsistency: A function's argument and return types must exist in a consistent universe, but ~a lives in universe (Type ~a) while ~a lives in universe (Type ~a)"))
 #'(void)]
```

**Comment by stchang** [comment]
fixed with https://github.com/stchang/macrotypes/commit/2840ef5313e9a7564aae965f0064674635474d28
