### ISSUE TITLE
Resugaring fails when syntax is missing a 'display-as property

### ISSUE THREAD

**Issue by wilbowma** [stchang/macrotypes#79]
https://github.com/stchang/macrotypes/blob/aacb1a9da998bdf40c4fc296839be1170374d9aa/turnstile-lib/turnstile/typedefs.rkt#L90

This line fails to account for the case when the `syntax-property` `'display-as` is missing, and thus `reflected-name` is `#f`, causing a contract error. In a large example, this somehow caused type checking to succeed when it shouldn't have, perhaps because an error happened in error handling code.

A simple fix is to add a `#:when reflect-name`, but I suspect this is not right fix.

**Comment by stchang** [comment]
Yes, that line should probably be wrapped with an `(and reflect-name ...)`

**Comment by stchang** [comment]
merged c2114c230168c43a147aa2044972a6ee9cbbe759
