### ISSUE TITLE
(U Bottom String) should not be a subtype of Bottom

### ISSUE THREAD

**Issue by AlexKnauth** [stchang/macrotypes#8]
I've come across a situation where there is a union that contains both Bottom and another type like `String`, and a type rule is testing whether that type is a subtype of Bottom. This should fail, but it succeeds.

The type `(U (U) String)` should be equivalent to `String`. It should not be a subtype of `(U)`, but this test shows that it is:
```racket
(typecheck-fail
 (λ ([x : (U (U) String)])
   (ann x : (U)))
 #:with-msg
 "expected \\(U\\), given String") ; either String or (U (U) String), they should be equivalent
; --------------------
; FAILURE
; name:       typecheck-fail
; location:   unsaved-editor:5:0
; params:     ((λ ((x : (U (U) String))) (ann x : (U))) "expected \\(U\\), given String")
; expected:   "expected \\(U\\), given String"
; message:    "No exception raised"
; expression: (typecheck-fail (λ ((x : (U (U) String))) (ann x : (U))) #:with-msg "expected \\(U\\), given String")
;
; . Check failure
; --------------------
```

**Comment by stchang** [comment]
The problem must be in the flattening done by the `U` constructor?

**Comment by AlexKnauth** [comment]
Yes, the `syntax->datum` of the type is `(#%app U*14 (lambda () (#%expression void)))`.

**Comment by AlexKnauth** [comment]
Ope, I think I found it. This code checks whether the list `tys-` is of length 1, but if it is it takes the first element of a different list, `tys` without the `-`.

```racket
     (if (= 1 (stx-length #'tys-))
         (stx-car #'tys)
         #'(U* . tys-))
```
It should use `(stx-car #'tys-)` instead.

**Comment by stchang** [comment]
Yep, just saw it too. Make sure to add the extra test.
