### ISSUE TITLE
(define-typed-variable id typed-e ⇐ τ) discards τ

### ISSUE THREAD

**Issue by tov** [stchang/macrotypes#84]
The form `(define-typed-variable id typed-e ⇐ τ)` is supposed to infer the type of `typed-e`, check that type against `τ`, and then bind `id` to the type-erasure of `typed-e`. So far as I can tell, it actually ignores the given `τ`, and is thus equivalent to `(define-typed-variable id typed-e)`. 

From the macro stepper, it looks like it creates a call to `(add-expected typed-e τ)` that is discarded before `typed-e` is checked.

This is with Racket 7.3 and the turnstile master 5111e55fd15ef2284455085b7bf770736dc12235. (I just ran `raco pkg update -a`.)

### Minimal example

The languages below include a type-annotated definition form `(def x τ e)`, which is supposed to check whether `e` has type `τ`. There’s a faulty definition of `def` in module `my-lang`, and then module `broken-example` demonstrates code using `def` that shouldn't type check but does.

Two workarounds follow:

  - Desugar `(def x τ e)` to `(define-typed-variable x (ann e τ))`.

  - Manually check `e` and type-erase it to `e-`; then expand into `(define-typed-variable x e- ⇒ τ)`.

Both workarounds implement the desired semantics, but only the latter produces good error messages.

```racket
#lang racket/base

(module my-lang turnstile/lang
  (provide (all-defined-out))

  (define-base-types num str)

  ; This doesn't work.
  (define-typed-syntax def
    [(_ x:id t:type e:expr) ≫
     ----
     [≻ (define-typed-variable x e ⇐ t.norm)]])

  (define-typed-syntax ann
    [(_ e:expr t:type)
     ≫
     [⊢ e ≫ e- ⇐ t.norm]
     ----
     [⊢ e- ⇒ t.norm]])     

  (define-typed-syntax #%datum
    [(_ . n:number) ≫
     ----
     [⊢ 'n ⇒ num]]
    [(_ . s:string) ≫
     ----
     [⊢ 's ⇒ str]]))

(module broken-example (submod ".." my-lang)
  (def good-x num 5)
  (def good-y str "5")
  (ann good-x num)
  (ann good-y str)
  ;;; Should error, but doesn't:
  (def bad-x str 5)
  (def bad-y num "5")
  (ann bad-x num)
  (ann bad-y str))


(module workaround1 turnstile/lang
  (provide def (all-from-out (submod ".." my-lang)))
  (require (except-in (submod ".." my-lang) def))

  ; Expands using `ann`:
  (define-typed-syntax def
    [(_ x:id t:type e:expr) ≫
     ----
     [≻ (define-typed-variable x (ann e t))]]))

(module workaround2 turnstile/lang
  (provide def (all-from-out (submod ".." my-lang)))
  (require (except-in (submod ".." my-lang) def))

  ; Checks manually:
  (define-typed-syntax def
    [(_ x:id t:type e:expr)
     ≫
     [⊢ e ≫ e- ⇐ t.norm]
     ----
     [≻ (define-typed-variable x e- ⇒ t.norm)]]))

(module working-example1 (submod ".." workaround1)
  (def good-x num 5)
  (def good-y str "5")
  ;;; Errors, as it should:
  #;(def bad-x str 5)
  #;(def bad-y num "5"))

(module working-example2 (submod ".." workaround2)
  (def good-x num 5)
  (def good-y str "5")
  ;;; Errors, as it should:
  #;(def bad-x str 5)
  #;(def bad-y num "5"))
```

### Version details

```console
$ racket --version
Welcome to Racket v7.3.
$ raco pkg show
Installation-wide:
 Package            Checksum             Source
 main-distribution  c1122917ba1e292a...  catalog...tribution
 racket-lib         3844fcf1e76ef3e5...  catalog racket-lib
 [199 auto-installed packages not shown]
User-specific for installation "7.3":
 Package             Checksum             Source
 drracket-solarized  9a90657bb320d423...  catalog...ed/master
 turnstile           5111e55fd15ef228...  catalog...turnstile
 [17 auto-installed packages not shown]
```

**Comment by tov** [comment]
Sorry, I accidentally submitted this before I meant too. I’m fixing it now.

**Comment by tov** [comment]
Hopefully this is easy to fix and the big bug report is overkill.

**Comment by stchang** [comment]
Yes it's a bug. Bug report is very useful and not overkill, thanks.

The `define-typed-variable` `⇐` case should have the same behavior as the `⇐` judgement, but it mistakenly uses `add-expected`, which doesnt actually check, to do this.

**Comment by tov** [comment]
Cool. I’ll stop trying to fix it then, since I don’t understand what I’m doing.

**Comment by stchang** [comment]
The straightforward thing to do is for the first case, instead of delegating to the second, to just duplicate what the second does but with an extra check, eg something like (I didn't try running it so may need tweaking):

```
(define-syntax define-typed-variable
  (syntax-parser
    [(_ x:id e (~literal ⇐) τ) ; e typed, checked to have type τ
     #:with [e- τe] (infer+erase #'(add-expected e τ))
   #:with τ-expected (get-expected-type #'e-)
    #:fail-unless ((current-typecheck-relation) #'τe #'τ-expected) (typecheck-fail-msg/1 #'τ-expected #'τe #'e-)))
     (quasisyntax/loc this-syntax (define-typed-variable x e- ⇒ τe))]
    [(_ x:id e)
     #:with [e- τ] (infer+erase #'e)
     (quasisyntax/loc this-syntax (define-typed-variable x e- ⇒ τ))]
...
```

(This isnt completely satisfying because essentially duplicates the check rule, ie [here](https://github.com/stchang/macrotypes/blob/master/turnstile-lib/turnstile/turnstile.rkt#L191-L200). Somehow the checking got baked into pattern but I need to think about it more to determine what to abstract.)
